version: '3'


services:
    db:
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432"
        environment:
            - POSTGRES_DB=blog_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
    redis:
        image: "redis:alpine"
    web:
        build: .
        command: bash -c "python src/manage.py migrate --noinput && python src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    celery:
        build: src/
        command: bash -c "cd src && celery -A core worker -l info"
        volumes:
            - .:/code
        depends_on:
            - db
            - redis

volumes:
    postgres_data:
